import Head from 'next/head';
import { Dancing_Script } from 'next/font/google';
import styles from '@/styles/Home.module.scss';
import dynamic from 'next/dynamic';
import { useEffect, useRef, useState } from 'react';

const SectionA = dynamic(() => import('../components/SectionA'));
const SectionB = dynamic(() => import('../components/SectionB'));
const SectionC = dynamic(() => import('../components/SectionC'));
const SectionD = dynamic(() => import('../components/SectionD'));
const SectionE = dynamic(() => import('../components/SectionE'));

const dancingScript = Dancing_Script({
  display: 'swap',
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  style: ['normal'],
});
console.log(dancingScript);

export default function Home() {
  const [visibleSections, setVisibleSections] = useState([]);

  const sectionBRef = useRef(null);
  const sectionCRef = useRef(null);
  const sectionDRef = useRef(null);
  const sectionERef = useRef(null);

  useEffect(() => {
    const refs = {
      sectionBRef,
      sectionCRef,
      sectionDRef,
      sectionERef,
    };
    console.log(refs);
    const observer = new IntersectionObserver(
      (elements, ob) => {
        for (let el of elements) {
          if (el.isIntersecting && !visibleSections.includes(el.target.id)) {
            setVisibleSections([...visibleSections, el.target.id]);

            ob.unobserve(el.target);
          }
        }
      },
      {
        root: undefined,
        rootMargin: '0px',
        threshold: 0.5,
      }
    );

    for (let ref in refs) {
      if (!visibleSections.includes(ref)) {
        observer.observe(refs[ref].current);
      }
    }

    return () => observer.disconnect();
  }, [visibleSections]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={[styles.main, dancingScript.className, 'page-root'].join(' ')}>
        <SectionA />
        <section
          id="SectionB"
          style={{ minHeight: '600px', marginTop: '150px', backgroundColor: 'coral', width: '100%' }}
          ref={sectionBRef}
        >
          {visibleSections.includes('SectionB') && <SectionB />}
        </section>
        <section
          id="SectionC"
          style={{ minHeight: '600px', marginTop: '150px', backgroundColor: 'coral', width: '100%' }}
          ref={sectionCRef}
        >
          {visibleSections.includes('SectionC') && <SectionC />}
        </section>
        <section
          id="SectionD"
          style={{ minHeight: '600px', marginTop: '150px', backgroundColor: 'coral', width: '100%' }}
          ref={sectionDRef}
        >
          {visibleSections.includes('SectionD') && <SectionD />}
        </section>
        <section
          id="SectionE"
          style={{ minHeight: '600px', marginTop: '150px', backgroundColor: 'coral', width: '100%' }}
          ref={sectionERef}
        >
          {visibleSections.includes('SectionE') && <SectionE />}
        </section>
      </main>
    </>
  );
}
